name = "purehugo-kerkerj"
description = "A theme based on the pure css blog layout forked from purehugo"
license = "MIT"
source_repo = "https://github.com/kerkerj/purehugo"
tags = ["blog", "purecss"]
min_version = 0.13

[author]
    name = "kerkerj"
    twitter = "http://twitter.com/kerkerj"
    url = "http://github.com/kerkerj"
